### ISSUE TITLE
Problem with styling CTextBlock.Heading*

### ISSUE THREAD

**Issue by ElrohirGT** [whistyun/Markdown.Avalonia#71]
Hi! I'm currently developing an Avalonia app that has support for multiple themes. The main window shows the CHANGELOG of the application parsing the current .md thats hosted in the web.

Heres the xaml:
```xaml
<ScrollViewer Background="{DynamicResource SolidBackgroundFillColorBaseBrush}">
    <ScrollViewer.Styles>
        <Style Selector="ctxt|CTextBlock.Heading1">
            <Setter Property="Foreground" Value="{DynamicResource DefaultTextForegroundThemeBrush}"/>
        </Style>
    </ScrollViewer.Styles>
    <md:MarkdownScrollViewer
        Margin="5"
        Source="https://chemistry-tools.netlify.app/CHANGELOG.md"/>
</ScrollViewer>
```
The problem is when I change the theme to dark, the foreground color of the Headings doesn't change. This is weird because all the others do change. I tried creating a style but even though avalonia recognizes that my styles exist, it doesn't apply it.

Light theme (for reference):
![image](https://user-images.githubusercontent.com/45268815/165436650-3c753ac9-a3d3-412a-83cb-c236b74dd59c.png)
Dark Theme (the headings do not change color):
![image](https://user-images.githubusercontent.com/45268815/165436700-1f23b8b3-0f6b-41bf-b96a-414e7c81393a.png)
The avalonia debugger shows the styles are recognized for the correct element but are not applied:
![image](https://user-images.githubusercontent.com/45268815/165436838-33959029-795b-442d-a619-19c1246126e0.png)

If someone knows a workaround or can help point in the right direction would be greatly appreciated.

**Comment by whistyun** [comment]
Because MarkdownScrollViewer has its own style, the style of the parent control has lower priority.
The style has to be held in MarkdownScrollViewer.

```xml
<ScrollViewer Background="{DynamicResource SolidBackgroundFillColorBaseBrush}">
    <md:MarkdownScrollViewer
        Margin="5"
        Source="https://chemistry-tools.netlify.app/CHANGELOG.md">

    <md:MarkdownScrollViewer.Styles>
        <Style Selector="ctxt|CTextBlock.Heading1">
            <Setter Property="Foreground" Value="{DynamicResource DefaultTextForegroundThemeBrush}"/>
        </Style>
        <Style Selector="ctxt|CTextBlock.Heading2">
            <Setter Property="Foreground" Value="{DynamicResource DefaultTextForegroundThemeBrush}"/>
        </Style>
        <!-- and Heading3, Heading4 -->
    </md:MarkdownScrollViewer.Styles>

    <md:MarkdownScrollViewer>
</ScrollViewer>

```

If you want to look the style which are automatically applied to MarkdownScrollViewer, please see [this directory](https://github.com/whistyun/Markdown.Avalonia/tree/master/Markdown.Avalonia.Tight/StyleCollections).
[MarkdownStyleFluentTheme.axaml](https://github.com/whistyun/Markdown.Avalonia/blob/master/Markdown.Avalonia.Tight/StyleCollections/MarkdownStyleFluentTheme.axaml) is applied when you use Avalonia.Themes.Fluent.
[MarkdownStyleDefaultTheme.axaml](https://github.com/whistyun/Markdown.Avalonia/blob/master/Markdown.Avalonia.Tight/StyleCollections/MarkdownStyleDefaultTheme.axaml) is applied when you use Avalonia.Theme.Default.
If you use neither Avalonia.Themes.Fluent nor Avalonia.Theme.Default, [MarkdownStyleStandard.axaml](https://github.com/whistyun/Markdown.Avalonia/blob/master/Markdown.Avalonia.Tight/StyleCollections/MarkdownStyleStandard.axaml) is applied.

**Comment by ElrohirGT** [comment]
OOOH, THAT'S RIGHT! I didn't remember the priority of the styles in Avalonia. Thank you!

Currently I'm not using any of the themes you mention. I'm actually using a library callend FluentAvalonia.
App.xaml:
```xaml
<Application.Styles>
    <sty:FluentAvaloniaTheme />
</Application.Styles>
```
I suppose this means MarkdownStyleStandard.axaml is applied then?
